name: dotlynx_task
description: A new Flutter application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  dio: ^4.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh: ^2.0.0
  responsive_framework: ^0.1.9
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf